sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ChUeMBCHSgvHKtnQoOnLr63DROH0GhcFlIK2T/hUvt1FB3NClnd7aQkDltOIB4qljxG//nL8StFTTP/pFHKlc5GtR85NAqpGNqgbMNg8iK9JL0iAijxUO/bKIQSrUFIMwITVJMFincIWTdxlmJQe3cxUKoobowVOmN5PnafjGaETn3kjAL+2fP65hedu+equSoWegxd2I6Ftan/weOGTuvUAhrIrMk7wUjoDLVvpY9YH0QtRa/+ED8dndR0cSVysSqVhIWQdudaJCzOAec2MqumX85T+1/wnXgjSYhiCryLjbzMIDX3Yl5/XiSK8qE/fWLuu4Fw/6Bga4wFdgPDQ0L9xuXr+06LUHn8YzY4SxcGVysfTHHnOX3synrfX8K+3dIMqI2G8MuP4mNSzJ+iWRobgmtnwO6ZYpVFuCMpIIqQNay1LXxdFk/p4yzxTFg7jK3a7FFH5cHxDcphaIEByxkRc7cdhe/t6IcWfkO7K5x4nry2FHzNNYvgyDyRd5cWuyFk42fjfGPiLds+Z0AStrHiXRaD7v2yBgzs7lcJHr2r5eejqX2SA1Y5baV7WhBCSkPVCTkcQXBTsMNZ9DDqwd3NbMViVU6wQbhhSB1osI6kWpqiRyw05LLuQeVHpm21BX6iAAKUKOmrSGTcvANk50hPt+xEJ1esSqSUbczilJKw=
  - secure: IQ1gmzKG0M6pq4XnIi/IqDTLZwlVv7T5jPUSO820My49ANCdKnogPr4etJ81u+SoZt4LA1CS24nW6JLbQpFw1gx3+GtQ5jls2YY4M1KC+XQVySDpaqz4Lq26WkgscrHXNQYPfOmXVDRWuMDjXgIpEo4G1UM9VhmrT0JT4Jw6rKUxGkemkkYgUE14eG7it6+Ak+CbITq70Zwc3n7ItJFgQikokfW8fecOIKOW3SjCHTVPSD9xkPAa7LpL6ItjqFqHBeIAS9w9Jhpx/X3qJbSG1udhlJoUqIrGVfFRhuNt2x51khSo1MgqvnEFwuzxw5b73YjLE6lILuGkynDxsamD8ovg7YZbQ7wiWRQpDzuDgzNI+r2PX0maYG2C926zaRAIlItJ1yXzFv1lEDhhKZ7QoPxavLdHvgcOhVQsr3U0fcUT/rIoic7iSLAj2Xtx6mrzoWsDZXGGJx3J1Q18bnpP1v8w6TZz2yHLZ6EjnzcMLWOjZrJxA3X6Itl54UOUasmAP9ELdIKGnLjR0+sFTSL9TL+wfNbqwAgdXbeLklLMVBDKDr1p9AVjgvtcin3HrPGtQeUqFMYlifoeZJjFD/7ykBDTUs4CNQma2LilqLVYq4ZyKk+SNhQ1JFd03mUQXmDPQgiFpi4K9puhJDjTrfH95xgQ2t8+KS5SKtO/wlOtmz4=
  - secure: fqrBJ9kH5D3LeSE9JqEVWl8d/7f1ozYKGs5azOtmWh1ZaDwlseqDXkbntHe0ALi+gXWJxW0zTP0bv6idU4XLVcMPFhJmJ50Wm3rn0RYPE+nXL8/3hnhCnJvDd1p39oJN2l9+oa4gN6gSEIAEEspsPjGsdFPBe1DfxkJxFOuEb4H6UNEAh4YTbqtwVm4DgvY0QeGJwb93uIPz+szsThCklsuQbKBEL8FLNOlwI/oqXqa7TptA2gKWS5BYQTJasno8oPIzMW/TnMbQPucCdXdcMv633e1USLm2Y4Yod4dbH9m13BIih/JnBjkBjWXZRkrKIZW5rjJnpP/Sp9tlOupyZHsWW/4Ks6y5vy0sOm4KuYuegpRbr9BJ/ShDXTF5UA7Rj16GaUY4N6tJYiyTM40yTKvoY89PYn1dvVA6fE4q+qEgMWYjLtRACy0J6/Uro6fBFpvqj89ZuZCEClBcvbm+7OkvaJOPsB5W8KJubq9iStegB2btrEmeCm2FCBdHxK9DPBX5m07T0SDKgH17Og/Y/BjfvgH9sWOzqB89w5/jhNF/ZZ0Ho60rD6hJsLdYTmHJfp3UdG806Yr+eHeYXM7yt3ZhwLGc6PUpW9c20V9NOp8kmfOVgOpjnm3wIftAvMtiWfTrsQrobMkV8m78Osb2IsKyjqrvG8PZkEEU6b/FQtc=
  - secure: ku9yUeD6q3gE/MrwUaXhFjsBQ/+aWQyKUQE3j3RB5d4/jf6FzyIaiYyzURE7qDdKfmIpAKWUzDpoHubYB6nDd8qhvtgzZuvHYuHZCqyZClAOLm3sStX998Gz94lXMI887l3x0YdJqlIADq9xvArozhlcOYWK7y27uELR3Y/WibxI8f/Trx+j/+qNZyoV8NJL78mTzUg13Lu+OpZW+b1YFg6Z25AgFZYDJUWyIwST5+Xa1YknhJ7oaYKL4Fe/DVt/tas/97z7Iov6bvHs8Q3mDxJv0lbtQ+KQRv39jlTEmi9fVnikh0rB8QgHAl98C5h4QFTBcSuCrO/YV55TDsX0Hx91ZkTfMKdP4PoKDAygcVmYIY08rfdsX/ZWmn9FBDXc9aPxH9H2g1CjbLpfE1m064v7wMu6V6mVmhjeZ6JHUuaVyNNxPxIG303riqHhykyZSeub9gFfJVAIY0cUyLNFesPt55euLbRV88H9PsMqs1HLEgZ4ePycJw580llSCXCOZyk6WVsmKaqhHYexBWbBz45PGZRqouvddH4kU8ZBxdwXPff786sLR8vYht5Kyfz/AUphcD2o0yuWXipngr0cArJv+kRvoo5oHLkYousu9i/KRKAGfuKy5Hll8GYlDhKefBUn6lPKeXmd9d+ZIT9iTDcW2IrY4O2ayfsD4Ye3Urk=
