sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ChUeMBCHSgvHKtnQoOnLr63DROH0GhcFlIK2T/hUvt1FB3NClnd7aQkDltOIB4qljxG//nL8StFTTP/pFHKlc5GtR85NAqpGNqgbMNg8iK9JL0iAijxUO/bKIQSrUFIMwITVJMFincIWTdxlmJQe3cxUKoobowVOmN5PnafjGaETn3kjAL+2fP65hedu+equSoWegxd2I6Ftan/weOGTuvUAhrIrMk7wUjoDLVvpY9YH0QtRa/+ED8dndR0cSVysSqVhIWQdudaJCzOAec2MqumX85T+1/wnXgjSYhiCryLjbzMIDX3Yl5/XiSK8qE/fWLuu4Fw/6Bga4wFdgPDQ0L9xuXr+06LUHn8YzY4SxcGVysfTHHnOX3synrfX8K+3dIMqI2G8MuP4mNSzJ+iWRobgmtnwO6ZYpVFuCMpIIqQNay1LXxdFk/p4yzxTFg7jK3a7FFH5cHxDcphaIEByxkRc7cdhe/t6IcWfkO7K5x4nry2FHzNNYvgyDyRd5cWuyFk42fjfGPiLds+Z0AStrHiXRaD7v2yBgzs7lcJHr2r5eejqX2SA1Y5baV7WhBCSkPVCTkcQXBTsMNZ9DDqwd3NbMViVU6wQbhhSB1osI6kWpqiRyw05LLuQeVHpm21BX6iAAKUKOmrSGTcvANk50hPt+xEJ1esSqSUbczilJKw=
  - secure: IQ1gmzKG0M6pq4XnIi/IqDTLZwlVv7T5jPUSO820My49ANCdKnogPr4etJ81u+SoZt4LA1CS24nW6JLbQpFw1gx3+GtQ5jls2YY4M1KC+XQVySDpaqz4Lq26WkgscrHXNQYPfOmXVDRWuMDjXgIpEo4G1UM9VhmrT0JT4Jw6rKUxGkemkkYgUE14eG7it6+Ak+CbITq70Zwc3n7ItJFgQikokfW8fecOIKOW3SjCHTVPSD9xkPAa7LpL6ItjqFqHBeIAS9w9Jhpx/X3qJbSG1udhlJoUqIrGVfFRhuNt2x51khSo1MgqvnEFwuzxw5b73YjLE6lILuGkynDxsamD8ovg7YZbQ7wiWRQpDzuDgzNI+r2PX0maYG2C926zaRAIlItJ1yXzFv1lEDhhKZ7QoPxavLdHvgcOhVQsr3U0fcUT/rIoic7iSLAj2Xtx6mrzoWsDZXGGJx3J1Q18bnpP1v8w6TZz2yHLZ6EjnzcMLWOjZrJxA3X6Itl54UOUasmAP9ELdIKGnLjR0+sFTSL9TL+wfNbqwAgdXbeLklLMVBDKDr1p9AVjgvtcin3HrPGtQeUqFMYlifoeZJjFD/7ykBDTUs4CNQma2LilqLVYq4ZyKk+SNhQ1JFd03mUQXmDPQgiFpi4K9puhJDjTrfH95xgQ2t8+KS5SKtO/wlOtmz4=
